dist: trusty

language: ruby

addons:
  postgresql: "9.6"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3

script:
  - bin/rails db:test:prepare
  - RAILS_ENV=test bin/rspec


